$swaggerUrl = "https://api.test.missioncontrol.io/swagger/PartnerV2_0/swagger.json"
$swaggerFile = "swagger.json"

# Download file as raw text
$json = Invoke-WebRequest $swaggerUrl -UseBasicParsing | Select-Object -ExpandProperty Content

Write-Host "Fixing server url and paths"

# Step 1: Remove all /partnerApi/v2
$json = $json -replace "/partnerApi/v2", ""

# Step 2: Add /partnerApi/v2 after domain in server urls
# Matches: "url": "https://something"
$json = $json -replace '("url"\s*:\s*"(https?:\/\/[^"]+))"', '$1/partnerApi/v2"'

# Save result
Set-Content -Path $swaggerFile -Value $json -Encoding UTF8

Write-Host "Updating dotnet"

$csharpOutput = "./dotnet/src/MissionControl.Client/Generated"
kiota generate `
    --openapi $swaggerFile `
    --additional-data false `
    --language csharp `
    --output $csharpOutput `
    --class-name Client `
    --clean-output `
    --namespace-name MissionControl.Client.Generated

<#
    Patches C# code generated by kiota.
    Workaround for bug at https://github.com/microsoft/kiota/issues/3944#issuecomment-2597201229.
#>

# $osLineBreak = [System.Environment]::NewLine
# $files = Get-ChildItem -Path $csharpOutput -Recurse -Include *.cs

# foreach ($file in $files)
# {
#     $content = Get-Content $file -Raw

#     # add #nullable enable, suppress warning CS8625: Cannot convert null literal to non-nullable reference type.
#     $content = ($content -replace '// <auto-generated/>', "// <auto-generated/>$osLineBreak#nullable enable$osLineBreak#pragma warning disable CS8625")

#     # remove conditionals
#     $content = ($content -replace "(?s)#if NETSTANDARD2_1_OR_GREATER .*?$osLineBreak#nullable enable$osLineBreak(?<ifBody>.*?)$osLineBreak#nullable restore$osLineBreak#else$osLineBreak(?<elseBody>.*?)$osLineBreak#endif", "`$1")

#     # insert new line between member and next summary
#     $content = ($content -replace "}$osLineBreak(?<indentedSummary>\s+/// <summary>)", "}$osLineBreak$osLineBreak`$1")

#     Set-Content -Path $file -Value $content
# }


# Write-Host "Updating typescript"

# kiota generate `
#     --openapi $swaggerFile `
#     --additional-data false `
#     --language typescript `
#     --output ./typescript/src/client/generated `
#     --class-name client `
#     --namespace-name missioncontrol.client
